-- Seed design templates
-- Run this in Supabase SQL Editor

INSERT INTO design_templates (name, type, style, tags, description, json_structure) VALUES
('Services Colorful Grid', 'services', 'playful', ARRAY['services', 'colorful', 'grid'], 'Colorful service cards with icons', '{"type":"section","name":"Services","styles":{"display":"flex","flexDirection":"column","padding":80,"gap":48,"backgroundColor":"#ffffff"},"children":[{"type":"text","name":"Title","content":"My Services","styles":{"fontSize":32,"fontWeight":700,"color":"#000"}},{"type":"row","name":"Grid","styles":{"display":"flex","gap":24,"flexWrap":"wrap"},"children":[{"type":"frame","name":"Card1","styles":{"flex":1,"minWidth":200,"padding":24,"backgroundColor":"#FFC9F0","borderRadius":16},"children":[{"type":"text","name":"Title","content":"Branding","styles":{"fontSize":20,"fontWeight":700}}]},{"type":"frame","name":"Card2","styles":{"flex":1,"minWidth":200,"padding":24,"backgroundColor":"#FFE68C","borderRadius":16},"children":[{"type":"text","name":"Title","content":"Web Design","styles":{"fontSize":20,"fontWeight":700}}]},{"type":"frame","name":"Card3","styles":{"flex":1,"minWidth":200,"padding":24,"backgroundColor":"#9DDCFF","borderRadius":16},"children":[{"type":"text","name":"Title","content":"Development","styles":{"fontSize":20,"fontWeight":700}}]}]}]}');

INSERT INTO design_templates (name, type, style, tags, description, json_structure) VALUES
('Projects Portfolio Grid', 'projects', 'playful', ARRAY['portfolio', 'projects', 'gallery'], 'Project cards with images', '{"type":"section","name":"Projects","styles":{"display":"flex","flexDirection":"column","padding":80,"gap":48,"backgroundColor":"#FFFBF5"},"children":[{"type":"text","name":"Title","content":"Featured Projects","styles":{"fontSize":32,"fontWeight":700}},{"type":"row","name":"Grid","styles":{"display":"flex","gap":24,"flexWrap":"wrap"},"children":[{"type":"frame","name":"Card1","styles":{"flex":1,"minWidth":280,"padding":12,"backgroundColor":"#9DDCFF","borderRadius":24},"children":[{"type":"image","name":"Image","src":"https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=600","styles":{"borderRadius":16,"aspectRatio":"16/9","objectFit":"cover"}},{"type":"text","name":"Title","content":"Brand Identity","styles":{"fontSize":20,"fontWeight":700,"marginTop":16}}]},{"type":"frame","name":"Card2","styles":{"flex":1,"minWidth":280,"padding":12,"backgroundColor":"#FFE68C","borderRadius":24},"children":[{"type":"image","name":"Image","src":"https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600","styles":{"borderRadius":16,"aspectRatio":"16/9","objectFit":"cover"}},{"type":"text","name":"Title","content":"Logo Design","styles":{"fontSize":20,"fontWeight":700,"marginTop":16}}]}]}]}');

INSERT INTO design_templates (name, type, style, tags, description, json_structure) VALUES
('Experience Timeline', 'experience', 'playful', ARRAY['experience', 'timeline', 'resume'], 'Experience cards with dates', '{"type":"section","name":"Experience","styles":{"display":"flex","flexDirection":"column","padding":80,"gap":48,"backgroundColor":"#FFFBF5"},"children":[{"type":"text","name":"Title","content":"My Experience","styles":{"fontSize":32,"fontWeight":700}},{"type":"row","name":"Grid","styles":{"display":"flex","gap":24,"flexWrap":"wrap"},"children":[{"type":"frame","name":"Card1","styles":{"flex":1,"minWidth":280,"padding":24,"backgroundColor":"#9DDCFF","borderRadius":16},"children":[{"type":"text","name":"Date","content":"2021 - Present","styles":{"fontSize":14,"color":"#666"}},{"type":"text","name":"Role","content":"Senior Designer","styles":{"fontSize":20,"fontWeight":700,"marginTop":8}},{"type":"text","name":"Desc","content":"Leading design projects for major clients","styles":{"fontSize":16,"color":"#333","marginTop":12}}]},{"type":"frame","name":"Card2","styles":{"flex":1,"minWidth":280,"padding":24,"backgroundColor":"#FFE68C","borderRadius":16},"children":[{"type":"text","name":"Date","content":"2019 - 2021","styles":{"fontSize":14,"color":"#666"}},{"type":"text","name":"Role","content":"Product Designer","styles":{"fontSize":20,"fontWeight":700,"marginTop":8}},{"type":"text","name":"Desc","content":"Designed user interfaces for web apps","styles":{"fontSize":16,"color":"#333","marginTop":12}}]}]}]}');

INSERT INTO design_templates (name, type, style, tags, description, json_structure) VALUES
('FAQ Accordion', 'faq', 'playful', ARRAY['faq', 'questions'], 'FAQ section with expandable items', '{"type":"section","name":"FAQ","styles":{"display":"flex","flexDirection":"column","padding":80,"gap":32,"backgroundColor":"#ffffff"},"children":[{"type":"text","name":"Title","content":"FAQ","styles":{"fontSize":32,"fontWeight":700}},{"type":"stack","name":"Questions","styles":{"display":"flex","flexDirection":"column","gap":16,"maxWidth":700},"children":[{"type":"frame","name":"Item1","styles":{"padding":24,"backgroundColor":"#9DDCFF","borderRadius":16},"children":[{"type":"text","name":"Q","content":"What services do you offer?","styles":{"fontSize":18,"fontWeight":600}}]},{"type":"frame","name":"Item2","styles":{"padding":24,"backgroundColor":"#9DDCFF","borderRadius":16},"children":[{"type":"text","name":"Q","content":"How long does a project take?","styles":{"fontSize":18,"fontWeight":600}}]},{"type":"frame","name":"Item3","styles":{"padding":24,"backgroundColor":"#9DDCFF","borderRadius":16},"children":[{"type":"text","name":"Q","content":"What is your pricing?","styles":{"fontSize":18,"fontWeight":600}}]}]}]}');

INSERT INTO design_templates (name, type, style, tags, description, json_structure) VALUES
('Footer Light', 'footer', 'light', ARRAY['footer', 'navigation'], 'Simple footer with links and copyright', '{"type":"section","name":"Footer","styles":{"display":"flex","flexDirection":"row","justifyContent":"space-between","alignItems":"center","padding":40,"paddingLeft":80,"paddingRight":80,"borderTop":"1px solid #eee","backgroundColor":"#fff"},"children":[{"type":"text","name":"Logo","content":"Studio","styles":{"fontSize":20,"fontWeight":700}},{"type":"row","name":"Links","styles":{"display":"flex","gap":24},"children":[{"type":"text","name":"Link1","content":"Twitter","styles":{"fontSize":14,"color":"#666"}},{"type":"text","name":"Link2","content":"Instagram","styles":{"fontSize":14,"color":"#666"}},{"type":"text","name":"Link3","content":"Dribbble","styles":{"fontSize":14,"color":"#666"}}]},{"type":"text","name":"Copyright","content":"2024 All rights reserved","styles":{"fontSize":14,"color":"#999"}}]}');

INSERT INTO design_templates (name, type, style, tags, description, json_structure) VALUES
('Solutions Dark Grid', 'services', 'dark', ARRAY['services', 'solutions', 'dark'], 'Dark themed service cards with numbers', '{"type":"section","name":"Solutions","styles":{"display":"flex","flexDirection":"column","padding":80,"gap":48,"backgroundColor":"#000"},"children":[{"type":"text","name":"Title","content":"Solutions","styles":{"fontSize":32,"fontWeight":600,"color":"#fff"}},{"type":"row","name":"Grid","styles":{"display":"flex","gap":16,"flexWrap":"wrap"},"children":[{"type":"frame","name":"Card1","styles":{"flex":1,"minWidth":200,"padding":24,"backgroundColor":"#1c1c1c","borderRadius":16},"children":[{"type":"text","name":"Num","content":"01.","styles":{"fontSize":14,"color":"rgba(255,255,255,0.5)"}},{"type":"text","name":"Title","content":"Brand Identity","styles":{"fontSize":18,"fontWeight":600,"color":"#fff","marginTop":24}},{"type":"text","name":"Desc","content":"Creating memorable visual identities","styles":{"fontSize":14,"color":"rgba(255,255,255,0.5)","marginTop":12}}]},{"type":"frame","name":"Card2","styles":{"flex":1,"minWidth":200,"padding":24,"backgroundColor":"#1c1c1c","borderRadius":16},"children":[{"type":"text","name":"Num","content":"02.","styles":{"fontSize":14,"color":"rgba(255,255,255,0.5)"}},{"type":"text","name":"Title","content":"Web Design","styles":{"fontSize":18,"fontWeight":600,"color":"#fff","marginTop":24}},{"type":"text","name":"Desc","content":"Beautiful functional websites","styles":{"fontSize":14,"color":"rgba(255,255,255,0.5)","marginTop":12}}]}]}]}');

INSERT INTO design_templates (name, type, style, tags, description, json_structure) VALUES
('Testimonials Dark', 'testimonials', 'dark', ARRAY['testimonials', 'reviews', 'dark'], 'Dark themed testimonial cards', '{"type":"section","name":"Testimonials","styles":{"display":"flex","flexDirection":"column","padding":80,"gap":48,"backgroundColor":"#000"},"children":[{"type":"text","name":"Title","content":"What Others Say","styles":{"fontSize":32,"fontWeight":600,"color":"#fff"}},{"type":"row","name":"Grid","styles":{"display":"flex","gap":16,"flexWrap":"wrap"},"children":[{"type":"frame","name":"Card1","styles":{"flex":1,"minWidth":280,"padding":24,"backgroundColor":"#141414","borderRadius":16},"children":[{"type":"row","name":"Author","styles":{"display":"flex","alignItems":"center","gap":12},"children":[{"type":"image","name":"Avatar","src":"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=96","styles":{"width":40,"height":40,"borderRadius":20,"objectFit":"cover"}},{"type":"text","name":"Name","content":"Sarah M.","styles":{"fontSize":14,"fontWeight":500,"color":"#fff"}}]},{"type":"text","name":"Quote","content":"Amazing work! They transformed our brand completely.","styles":{"fontSize":16,"color":"#fff","marginTop":16,"lineHeight":1.6}}]},{"type":"frame","name":"Card2","styles":{"flex":1,"minWidth":280,"padding":24,"backgroundColor":"#141414","borderRadius":16},"children":[{"type":"row","name":"Author","styles":{"display":"flex","alignItems":"center","gap":12},"children":[{"type":"image","name":"Avatar","src":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=96","styles":{"width":40,"height":40,"borderRadius":20,"objectFit":"cover"}},{"type":"text","name":"Name","content":"John P.","styles":{"fontSize":14,"fontWeight":500,"color":"#fff"}}]},{"type":"text","name":"Quote","content":"Professional and delivered on time.","styles":{"fontSize":16,"color":"#fff","marginTop":16,"lineHeight":1.6}}]}]}]}');

INSERT INTO design_templates (name, type, style, tags, description, json_structure) VALUES
('Pricing Cards', 'pricing', 'dark', ARRAY['pricing', 'plans', 'dark'], 'Pricing cards with features', '{"type":"section","name":"Pricing","styles":{"display":"flex","flexDirection":"column","padding":80,"gap":48,"backgroundColor":"#000"},"children":[{"type":"text","name":"Title","content":"Pricing","styles":{"fontSize":32,"fontWeight":600,"color":"#fff"}},{"type":"row","name":"Cards","styles":{"display":"flex","gap":24,"flexWrap":"wrap"},"children":[{"type":"frame","name":"Plan1","styles":{"flex":1,"minWidth":280,"padding":32,"backgroundColor":"#141414","borderRadius":16},"children":[{"type":"text","name":"Name","content":"Per Project","styles":{"fontSize":18,"fontWeight":600,"color":"#fff"}},{"type":"text","name":"Price","content":"$5000","styles":{"fontSize":32,"fontWeight":700,"color":"#fff","marginTop":16}},{"type":"text","name":"Period","content":"/project","styles":{"fontSize":14,"color":"rgba(255,255,255,0.5)"}},{"type":"button","name":"CTA","content":"Book a call","styles":{"backgroundColor":"#CAE8BD","color":"#000","padding":16,"borderRadius":50,"fontWeight":600,"marginTop":24,"width":"100%","textAlign":"center"}}]},{"type":"frame","name":"Plan2","styles":{"flex":1,"minWidth":280,"padding":32,"backgroundColor":"#141414","borderRadius":16},"children":[{"type":"text","name":"Name","content":"Monthly","styles":{"fontSize":18,"fontWeight":600,"color":"#fff"}},{"type":"text","name":"Price","content":"$2500","styles":{"fontSize":32,"fontWeight":700,"color":"#fff","marginTop":16}},{"type":"text","name":"Period","content":"/month","styles":{"fontSize":14,"color":"rgba(255,255,255,0.5)"}},{"type":"button","name":"CTA","content":"Book a call","styles":{"backgroundColor":"#CAE8BD","color":"#000","padding":16,"borderRadius":50,"fontWeight":600,"marginTop":24,"width":"100%","textAlign":"center"}}]}]}]}');

INSERT INTO design_templates (name, type, style, tags, description, json_structure) VALUES
('Features Grid SaaS', 'features', 'light', ARRAY['features', 'saas', 'grid'], 'Feature cards for SaaS landing', '{"type":"section","name":"Features","styles":{"display":"flex","flexDirection":"column","padding":80,"gap":48,"backgroundColor":"#fff"},"children":[{"type":"text","name":"Title","content":"Why Choose Us","styles":{"fontSize":32,"fontWeight":700,"color":"#000","textAlign":"center"}},{"type":"row","name":"Grid","styles":{"display":"flex","gap":12,"flexWrap":"wrap"},"children":[{"type":"frame","name":"Card1","styles":{"flex":1,"minWidth":300,"padding":48,"backgroundColor":"#fff","borderRadius":24,"border":"1px solid #eee"},"children":[{"type":"text","name":"Title","content":"Fast Interface","styles":{"fontSize":20,"fontWeight":700,"color":"#000"}},{"type":"text","name":"Desc","content":"Create in seconds with our lightning-fast platform","styles":{"fontSize":16,"color":"rgba(0,0,0,0.6)","marginTop":8}}]},{"type":"frame","name":"Card2","styles":{"flex":1,"minWidth":300,"padding":48,"backgroundColor":"#fff","borderRadius":24,"border":"1px solid #eee"},"children":[{"type":"text","name":"Title","content":"Analytics","styles":{"fontSize":20,"fontWeight":700,"color":"#000"}},{"type":"text","name":"Desc","content":"Track and measure everything that matters","styles":{"fontSize":16,"color":"rgba(0,0,0,0.6)","marginTop":8}}]},{"type":"frame","name":"Card3","styles":{"flex":1,"minWidth":300,"padding":48,"backgroundColor":"#fff","borderRadius":24,"border":"1px solid #eee"},"children":[{"type":"text","name":"Title","content":"Customization","styles":{"fontSize":20,"fontWeight":700,"color":"#000"}},{"type":"text","name":"Desc","content":"Make it yours with full branding control","styles":{"fontSize":16,"color":"rgba(0,0,0,0.6)","marginTop":8}}]}]}]}');

INSERT INTO design_templates (name, type, style, tags, description, json_structure) VALUES
('CTA Banner SaaS', 'cta', 'accent', ARRAY['cta', 'banner', 'saas'], 'Colorful CTA banner with button', '{"type":"section","name":"CTA","styles":{"display":"flex","flexDirection":"column","alignItems":"center","justifyContent":"center","padding":96,"gap":24,"backgroundColor":"#e11d48","borderRadius":24,"margin":24},"children":[{"type":"text","name":"Title","content":"Ready to get started?","styles":{"fontSize":32,"fontWeight":700,"color":"#fff","textAlign":"center"}},{"type":"text","name":"Subtitle","content":"Join thousands of happy customers today","styles":{"fontSize":18,"color":"rgba(255,255,255,0.8)","textAlign":"center"}},{"type":"button","name":"CTA","content":"Get started now","styles":{"backgroundColor":"#fff","color":"#e11d48","padding":16,"paddingLeft":32,"paddingRight":32,"borderRadius":50,"fontWeight":600}}]}');

INSERT INTO design_templates (name, type, style, tags, description, json_structure) VALUES
('Blog Cards', 'blog', 'light', ARRAY['blog', 'articles', 'cards'], 'Blog article cards with images', '{"type":"section","name":"Blog","styles":{"display":"flex","flexDirection":"column","padding":80,"gap":48,"backgroundColor":"#fff"},"children":[{"type":"text","name":"Title","content":"Latest Articles","styles":{"fontSize":32,"fontWeight":700}},{"type":"row","name":"Grid","styles":{"display":"flex","gap":24,"flexWrap":"wrap"},"children":[{"type":"frame","name":"Card1","styles":{"flex":1,"minWidth":280},"children":[{"type":"frame","name":"ImageBox","styles":{"backgroundColor":"#f5f5f5","borderRadius":24,"height":200,"border":"1px solid #eee"},"children":[]},{"type":"text","name":"Title","content":"Design Guidelines for Modern Web","styles":{"fontSize":18,"fontWeight":700,"marginTop":24}},{"type":"text","name":"Link","content":"Read more","styles":{"fontSize":14,"color":"#e11d48","fontWeight":600,"marginTop":16}}]},{"type":"frame","name":"Card2","styles":{"flex":1,"minWidth":280},"children":[{"type":"frame","name":"ImageBox","styles":{"backgroundColor":"#f5f5f5","borderRadius":24,"height":200,"border":"1px solid #eee"},"children":[]},{"type":"text","name":"Title","content":"Building Scalable Design Systems","styles":{"fontSize":18,"fontWeight":700,"marginTop":24}},{"type":"text","name":"Link","content":"Read more","styles":{"fontSize":14,"color":"#e11d48","fontWeight":600,"marginTop":16}}]}]}]}');
